name: pika_feedback_app_ex
description: this is feedback small app of pika company please use and review it thank you.
homepage: https://github.com/duythien0912/report-app-flutter
author: Duy Thien <duythien0912@gmail.com>

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies: 
  flutter: 
    sdk: flutter
  pika_feedback_app:
    path: ../
   
    
  
dev_dependencies:






flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
