name: pika_feedback_app
description: this is feedback small app of pika company please use and review it thank you.
homepage: http://pikatech.vn
author: Duy Thien <duythien0912@gmail.com>

version: 1.0.0+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.3 
  provider: ^3.0.0+1 
  image_picker: ^0.6.0+9

dev_dependencies:






flutter:

  
  
  
  uses-material-design: true

  
  assets: 
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
